name: Deploy Sphinx to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10 # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Build Sphinx documentation
        run: |
          make -C docs html  # Adjust 'docs' if your Sphinx files are located elsewhere

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
